### ISSUE TITLE
allowing custom snpEff databases

### ISSUE THREAD

**Issue by vmkalbskopf** [sanjaynagi/rna-seq-pop#39]
A new rule for creating custom snpEff databases.

**Comment by vmkalbskopf** [comment]
Building a custom database requires modifying snpEff files and directories. However, it is installed through conda by Snakemake, into a [randomly named folder](https://bioinformatics.stackexchange.com/questions/9334/snakemake-with-conda-prefix-can-i-use-a-pre-built-conda-environment) in the envs directory. 
I don't know how to modify the contents of that directory to build the custom DB.

**Comment by sanjaynagi** [comment]
Ok. What might be easier for now, is just run your snpEff version outside of the pipeline, but produce the files required by the workflow. Think they are called annot.variants.{chrom}.vcf.gz. Then you should be able to continue running the workflow. 
Cheers 

>

**Comment by vmkalbskopf** [comment]
Yeah, that's so much easier.

**Comment by sanjaynagi** [comment]
Yeah thats an option - the workflow actually used to require a manual installation of snpEff 5.0.0 as there was an error when downloading the Aedes_aegypti with snpEff 4.3.1. 

But i still probably think the best fix is to replace the snpSift dependency for bcftools, and that way we can use SnpEff 5.0.0 with conda. Better to have less depencies anyway, and bcftools is used anyway and almost certainly more reliable.
