### ISSUE TITLE
matplotlib can't import docstring causes error in checkinputs

### ISSUE THREAD

**Issue by azurillandfriend** [sanjaynagi/rna-seq-pop#93]
Possibly due to some change in matplotlib?
Last 3 lines of Checkinputs.log:
  
File "/usr/lib/python3/dist-packages/mpl_toolkits/mplot3d/axes3d.py", line 23, in <module>
    from matplotlib import _api, cbook, docstring, _preprocess_data
ImportError: cannot import name 'docstring' from 'matplotlib' (/home/dyern/lstm_scratch/rna-seq-pop/.snakemake/conda/bce977d41e12128f7e70506d022b4f3c/lib/python3.10/site-packages/matplotlib/__init__.py)

**Comment by sanjaynagi** [comment]
Hey Naomi, yeah, RNA-Seq-Pops conda env have been a bit messed up recently. Will try and fix tmw.

**Comment by sanjaynagi** [comment]
Have a go now, its working in CI and my computer, so should be OK

**Comment by sanjaynagi** [comment]
fixed by updating pythonGenomics.yaml - matplotlib==3.8.2, had a bug in 3.8.0
