### ISSUE TITLE
error in rule DifferentialIsoformExpression when running test dataset - possible sleuth/R problem?

### ISSUE THREAD

**Issue by azurillandfriend** [sanjaynagi/rna-seq-pop#96]
The test dataset was run as per the instructions in the tutorial by running the command:

snakemake --cores 4 --directory .test/ --use-conda --configfile .test/config/config_paired_end.yaml

The DAG indicated a total of 21 jobs to be run. 

The first error was "Error in rule DifferentialIsoformExpression". This appears to be because sleuth package is not loading in R
The full error file (logs/DifferentialIsoformExpression.log) is pasted below:

── Attaching packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.3.1 ──
✔ ggplot2 3.3.6      ✔ purrr   0.3.4
✔ tibble  3.1.8      ✔ dplyr   1.0.10
✔ tidyr   1.2.1      ✔ stringr 1.4.1
✔ readr   2.1.2      ✔ forcats 0.5.2
── Conflicts ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
Error: package or namespace load failed for ‘sleuth’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/dyern/lstm_scratch/rna-seq-pop/.snakemake/conda/b9a84f51ae3c40ad84a2205742a549eb/lib/R/library/rhdf5/libs/rhdf5.so':
  libcrypto.so.1.1: cannot open shared object file: No such file or directory
Execution halted
(py90) dyern@neptune2:~/lstm_scratch/rna-seq-pop$ less logs/DifferentialIsoformExpression.log
── Attaching packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.3.1 ──
✔ ggplot2 3.3.6      ✔ purrr   0.3.4
✔ tibble  3.1.8      ✔ dplyr   1.0.10
✔ tidyr   1.2.1      ✔ stringr 1.4.1
✔ readr   2.1.2      ✔ forcats 0.5.2
── Conflicts ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
Error: package or namespace load failed for ‘sleuth’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/dyern/lstm_scratch/rna-seq-pop/.snakemake/conda/b9a84f51ae3c40ad84a2205742a549eb/lib/R/library/rhdf5/libs/rhdf5.so':
  libcrypto.so.1.1: cannot open shared object file: No such file or directory
Execution halted

**Comment by azurillandfriend** [comment]
appending to comment. The file "/home/dyern/lstm_scratch/rna-seq-pop/.snakemake/conda/b9a84f51ae3c40ad84a2205742a549eb/lib/R/library/rhdf5/libs/rhdf5.so" does exist and has size 3959800

**Comment by sanjaynagi** [comment]
new version of sleuth fixes it in #107
